
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `TutorProfiles` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model TutorProfiles
 * 
 */
export type TutorProfilesModel = runtime.Types.Result.DefaultSelection<Prisma.$TutorProfilesPayload>

export type AggregateTutorProfiles = {
  _count: TutorProfilesCountAggregateOutputType | null
  _avg: TutorProfilesAvgAggregateOutputType | null
  _sum: TutorProfilesSumAggregateOutputType | null
  _min: TutorProfilesMinAggregateOutputType | null
  _max: TutorProfilesMaxAggregateOutputType | null
}

export type TutorProfilesAvgAggregateOutputType = {
  hourlyRate: number | null
  experience: number | null
  averageRating: number | null
}

export type TutorProfilesSumAggregateOutputType = {
  hourlyRate: number | null
  experience: number | null
  averageRating: number | null
}

export type TutorProfilesMinAggregateOutputType = {
  id: string | null
  userId: string | null
  bio: string | null
  hourlyRate: number | null
  experience: number | null
  averageRating: number | null
}

export type TutorProfilesMaxAggregateOutputType = {
  id: string | null
  userId: string | null
  bio: string | null
  hourlyRate: number | null
  experience: number | null
  averageRating: number | null
}

export type TutorProfilesCountAggregateOutputType = {
  id: number
  userId: number
  bio: number
  hourlyRate: number
  experience: number
  averageRating: number
  availability: number
  _all: number
}


export type TutorProfilesAvgAggregateInputType = {
  hourlyRate?: true
  experience?: true
  averageRating?: true
}

export type TutorProfilesSumAggregateInputType = {
  hourlyRate?: true
  experience?: true
  averageRating?: true
}

export type TutorProfilesMinAggregateInputType = {
  id?: true
  userId?: true
  bio?: true
  hourlyRate?: true
  experience?: true
  averageRating?: true
}

export type TutorProfilesMaxAggregateInputType = {
  id?: true
  userId?: true
  bio?: true
  hourlyRate?: true
  experience?: true
  averageRating?: true
}

export type TutorProfilesCountAggregateInputType = {
  id?: true
  userId?: true
  bio?: true
  hourlyRate?: true
  experience?: true
  averageRating?: true
  availability?: true
  _all?: true
}

export type TutorProfilesAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which TutorProfiles to aggregate.
   */
  where?: Prisma.TutorProfilesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TutorProfiles to fetch.
   */
  orderBy?: Prisma.TutorProfilesOrderByWithRelationInput | Prisma.TutorProfilesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.TutorProfilesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TutorProfiles from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TutorProfiles.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned TutorProfiles
  **/
  _count?: true | TutorProfilesCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: TutorProfilesAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: TutorProfilesSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: TutorProfilesMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: TutorProfilesMaxAggregateInputType
}

export type GetTutorProfilesAggregateType<T extends TutorProfilesAggregateArgs> = {
      [P in keyof T & keyof AggregateTutorProfiles]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateTutorProfiles[P]>
    : Prisma.GetScalarType<T[P], AggregateTutorProfiles[P]>
}




export type TutorProfilesGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.TutorProfilesWhereInput
  orderBy?: Prisma.TutorProfilesOrderByWithAggregationInput | Prisma.TutorProfilesOrderByWithAggregationInput[]
  by: Prisma.TutorProfilesScalarFieldEnum[] | Prisma.TutorProfilesScalarFieldEnum
  having?: Prisma.TutorProfilesScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: TutorProfilesCountAggregateInputType | true
  _avg?: TutorProfilesAvgAggregateInputType
  _sum?: TutorProfilesSumAggregateInputType
  _min?: TutorProfilesMinAggregateInputType
  _max?: TutorProfilesMaxAggregateInputType
}

export type TutorProfilesGroupByOutputType = {
  id: string
  userId: string
  bio: string | null
  hourlyRate: number
  experience: number | null
  averageRating: number
  availability: runtime.JsonValue
  _count: TutorProfilesCountAggregateOutputType | null
  _avg: TutorProfilesAvgAggregateOutputType | null
  _sum: TutorProfilesSumAggregateOutputType | null
  _min: TutorProfilesMinAggregateOutputType | null
  _max: TutorProfilesMaxAggregateOutputType | null
}

type GetTutorProfilesGroupByPayload<T extends TutorProfilesGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<TutorProfilesGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof TutorProfilesGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], TutorProfilesGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], TutorProfilesGroupByOutputType[P]>
      }
    >
  >



export type TutorProfilesWhereInput = {
  AND?: Prisma.TutorProfilesWhereInput | Prisma.TutorProfilesWhereInput[]
  OR?: Prisma.TutorProfilesWhereInput[]
  NOT?: Prisma.TutorProfilesWhereInput | Prisma.TutorProfilesWhereInput[]
  id?: Prisma.StringFilter<"TutorProfiles"> | string
  userId?: Prisma.StringFilter<"TutorProfiles"> | string
  bio?: Prisma.StringNullableFilter<"TutorProfiles"> | string | null
  hourlyRate?: Prisma.IntFilter<"TutorProfiles"> | number
  experience?: Prisma.IntNullableFilter<"TutorProfiles"> | number | null
  averageRating?: Prisma.FloatFilter<"TutorProfiles"> | number
  availability?: Prisma.JsonFilter<"TutorProfiles">
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  categories?: Prisma.CategoryListRelationFilter
  bookings?: Prisma.BookingsListRelationFilter
  reviews?: Prisma.ReviewListRelationFilter
}

export type TutorProfilesOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  bio?: Prisma.SortOrderInput | Prisma.SortOrder
  hourlyRate?: Prisma.SortOrder
  experience?: Prisma.SortOrderInput | Prisma.SortOrder
  averageRating?: Prisma.SortOrder
  availability?: Prisma.SortOrder
  user?: Prisma.UserOrderByWithRelationInput
  categories?: Prisma.CategoryOrderByRelationAggregateInput
  bookings?: Prisma.BookingsOrderByRelationAggregateInput
  reviews?: Prisma.ReviewOrderByRelationAggregateInput
}

export type TutorProfilesWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  userId?: string
  AND?: Prisma.TutorProfilesWhereInput | Prisma.TutorProfilesWhereInput[]
  OR?: Prisma.TutorProfilesWhereInput[]
  NOT?: Prisma.TutorProfilesWhereInput | Prisma.TutorProfilesWhereInput[]
  bio?: Prisma.StringNullableFilter<"TutorProfiles"> | string | null
  hourlyRate?: Prisma.IntFilter<"TutorProfiles"> | number
  experience?: Prisma.IntNullableFilter<"TutorProfiles"> | number | null
  averageRating?: Prisma.FloatFilter<"TutorProfiles"> | number
  availability?: Prisma.JsonFilter<"TutorProfiles">
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  categories?: Prisma.CategoryListRelationFilter
  bookings?: Prisma.BookingsListRelationFilter
  reviews?: Prisma.ReviewListRelationFilter
}, "id" | "userId">

export type TutorProfilesOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  bio?: Prisma.SortOrderInput | Prisma.SortOrder
  hourlyRate?: Prisma.SortOrder
  experience?: Prisma.SortOrderInput | Prisma.SortOrder
  averageRating?: Prisma.SortOrder
  availability?: Prisma.SortOrder
  _count?: Prisma.TutorProfilesCountOrderByAggregateInput
  _avg?: Prisma.TutorProfilesAvgOrderByAggregateInput
  _max?: Prisma.TutorProfilesMaxOrderByAggregateInput
  _min?: Prisma.TutorProfilesMinOrderByAggregateInput
  _sum?: Prisma.TutorProfilesSumOrderByAggregateInput
}

export type TutorProfilesScalarWhereWithAggregatesInput = {
  AND?: Prisma.TutorProfilesScalarWhereWithAggregatesInput | Prisma.TutorProfilesScalarWhereWithAggregatesInput[]
  OR?: Prisma.TutorProfilesScalarWhereWithAggregatesInput[]
  NOT?: Prisma.TutorProfilesScalarWhereWithAggregatesInput | Prisma.TutorProfilesScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"TutorProfiles"> | string
  userId?: Prisma.StringWithAggregatesFilter<"TutorProfiles"> | string
  bio?: Prisma.StringNullableWithAggregatesFilter<"TutorProfiles"> | string | null
  hourlyRate?: Prisma.IntWithAggregatesFilter<"TutorProfiles"> | number
  experience?: Prisma.IntNullableWithAggregatesFilter<"TutorProfiles"> | number | null
  averageRating?: Prisma.FloatWithAggregatesFilter<"TutorProfiles"> | number
  availability?: Prisma.JsonWithAggregatesFilter<"TutorProfiles">
}

export type TutorProfilesCreateInput = {
  id?: string
  bio?: string | null
  hourlyRate: number
  experience?: number | null
  averageRating?: number
  availability: Prisma.JsonNullValueInput | runtime.InputJsonValue
  user: Prisma.UserCreateNestedOneWithoutTutorProfilesInput
  categories?: Prisma.CategoryCreateNestedManyWithoutTutorProfilesInput
  bookings?: Prisma.BookingsCreateNestedManyWithoutTutorInput
  reviews?: Prisma.ReviewCreateNestedManyWithoutTutorInput
}

export type TutorProfilesUncheckedCreateInput = {
  id?: string
  userId: string
  bio?: string | null
  hourlyRate: number
  experience?: number | null
  averageRating?: number
  availability: Prisma.JsonNullValueInput | runtime.InputJsonValue
  categories?: Prisma.CategoryUncheckedCreateNestedManyWithoutTutorProfilesInput
  bookings?: Prisma.BookingsUncheckedCreateNestedManyWithoutTutorInput
  reviews?: Prisma.ReviewUncheckedCreateNestedManyWithoutTutorInput
}

export type TutorProfilesUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  bio?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  hourlyRate?: Prisma.IntFieldUpdateOperationsInput | number
  experience?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  averageRating?: Prisma.FloatFieldUpdateOperationsInput | number
  availability?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  user?: Prisma.UserUpdateOneRequiredWithoutTutorProfilesNestedInput
  categories?: Prisma.CategoryUpdateManyWithoutTutorProfilesNestedInput
  bookings?: Prisma.BookingsUpdateManyWithoutTutorNestedInput
  reviews?: Prisma.ReviewUpdateManyWithoutTutorNestedInput
}

export type TutorProfilesUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  bio?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  hourlyRate?: Prisma.IntFieldUpdateOperationsInput | number
  experience?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  averageRating?: Prisma.FloatFieldUpdateOperationsInput | number
  availability?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  categories?: Prisma.CategoryUncheckedUpdateManyWithoutTutorProfilesNestedInput
  bookings?: Prisma.BookingsUncheckedUpdateManyWithoutTutorNestedInput
  reviews?: Prisma.ReviewUncheckedUpdateManyWithoutTutorNestedInput
}

export type TutorProfilesCreateManyInput = {
  id?: string
  userId: string
  bio?: string | null
  hourlyRate: number
  experience?: number | null
  averageRating?: number
  availability: Prisma.JsonNullValueInput | runtime.InputJsonValue
}

export type TutorProfilesUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  bio?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  hourlyRate?: Prisma.IntFieldUpdateOperationsInput | number
  experience?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  averageRating?: Prisma.FloatFieldUpdateOperationsInput | number
  availability?: Prisma.JsonNullValueInput | runtime.InputJsonValue
}

export type TutorProfilesUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  bio?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  hourlyRate?: Prisma.IntFieldUpdateOperationsInput | number
  experience?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  averageRating?: Prisma.FloatFieldUpdateOperationsInput | number
  availability?: Prisma.JsonNullValueInput | runtime.InputJsonValue
}

export type TutorProfilesListRelationFilter = {
  every?: Prisma.TutorProfilesWhereInput
  some?: Prisma.TutorProfilesWhereInput
  none?: Prisma.TutorProfilesWhereInput
}

export type TutorProfilesOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type TutorProfilesCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  bio?: Prisma.SortOrder
  hourlyRate?: Prisma.SortOrder
  experience?: Prisma.SortOrder
  averageRating?: Prisma.SortOrder
  availability?: Prisma.SortOrder
}

export type TutorProfilesAvgOrderByAggregateInput = {
  hourlyRate?: Prisma.SortOrder
  experience?: Prisma.SortOrder
  averageRating?: Prisma.SortOrder
}

export type TutorProfilesMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  bio?: Prisma.SortOrder
  hourlyRate?: Prisma.SortOrder
  experience?: Prisma.SortOrder
  averageRating?: Prisma.SortOrder
}

export type TutorProfilesMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  bio?: Prisma.SortOrder
  hourlyRate?: Prisma.SortOrder
  experience?: Prisma.SortOrder
  averageRating?: Prisma.SortOrder
}

export type TutorProfilesSumOrderByAggregateInput = {
  hourlyRate?: Prisma.SortOrder
  experience?: Prisma.SortOrder
  averageRating?: Prisma.SortOrder
}

export type TutorProfilesScalarRelationFilter = {
  is?: Prisma.TutorProfilesWhereInput
  isNot?: Prisma.TutorProfilesWhereInput
}

export type TutorProfilesCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.TutorProfilesCreateWithoutUserInput, Prisma.TutorProfilesUncheckedCreateWithoutUserInput> | Prisma.TutorProfilesCreateWithoutUserInput[] | Prisma.TutorProfilesUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.TutorProfilesCreateOrConnectWithoutUserInput | Prisma.TutorProfilesCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.TutorProfilesCreateManyUserInputEnvelope
  connect?: Prisma.TutorProfilesWhereUniqueInput | Prisma.TutorProfilesWhereUniqueInput[]
}

export type TutorProfilesUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.TutorProfilesCreateWithoutUserInput, Prisma.TutorProfilesUncheckedCreateWithoutUserInput> | Prisma.TutorProfilesCreateWithoutUserInput[] | Prisma.TutorProfilesUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.TutorProfilesCreateOrConnectWithoutUserInput | Prisma.TutorProfilesCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.TutorProfilesCreateManyUserInputEnvelope
  connect?: Prisma.TutorProfilesWhereUniqueInput | Prisma.TutorProfilesWhereUniqueInput[]
}

export type TutorProfilesUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.TutorProfilesCreateWithoutUserInput, Prisma.TutorProfilesUncheckedCreateWithoutUserInput> | Prisma.TutorProfilesCreateWithoutUserInput[] | Prisma.TutorProfilesUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.TutorProfilesCreateOrConnectWithoutUserInput | Prisma.TutorProfilesCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.TutorProfilesUpsertWithWhereUniqueWithoutUserInput | Prisma.TutorProfilesUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.TutorProfilesCreateManyUserInputEnvelope
  set?: Prisma.TutorProfilesWhereUniqueInput | Prisma.TutorProfilesWhereUniqueInput[]
  disconnect?: Prisma.TutorProfilesWhereUniqueInput | Prisma.TutorProfilesWhereUniqueInput[]
  delete?: Prisma.TutorProfilesWhereUniqueInput | Prisma.TutorProfilesWhereUniqueInput[]
  connect?: Prisma.TutorProfilesWhereUniqueInput | Prisma.TutorProfilesWhereUniqueInput[]
  update?: Prisma.TutorProfilesUpdateWithWhereUniqueWithoutUserInput | Prisma.TutorProfilesUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.TutorProfilesUpdateManyWithWhereWithoutUserInput | Prisma.TutorProfilesUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.TutorProfilesScalarWhereInput | Prisma.TutorProfilesScalarWhereInput[]
}

export type TutorProfilesUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.TutorProfilesCreateWithoutUserInput, Prisma.TutorProfilesUncheckedCreateWithoutUserInput> | Prisma.TutorProfilesCreateWithoutUserInput[] | Prisma.TutorProfilesUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.TutorProfilesCreateOrConnectWithoutUserInput | Prisma.TutorProfilesCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.TutorProfilesUpsertWithWhereUniqueWithoutUserInput | Prisma.TutorProfilesUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.TutorProfilesCreateManyUserInputEnvelope
  set?: Prisma.TutorProfilesWhereUniqueInput | Prisma.TutorProfilesWhereUniqueInput[]
  disconnect?: Prisma.TutorProfilesWhereUniqueInput | Prisma.TutorProfilesWhereUniqueInput[]
  delete?: Prisma.TutorProfilesWhereUniqueInput | Prisma.TutorProfilesWhereUniqueInput[]
  connect?: Prisma.TutorProfilesWhereUniqueInput | Prisma.TutorProfilesWhereUniqueInput[]
  update?: Prisma.TutorProfilesUpdateWithWhereUniqueWithoutUserInput | Prisma.TutorProfilesUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.TutorProfilesUpdateManyWithWhereWithoutUserInput | Prisma.TutorProfilesUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.TutorProfilesScalarWhereInput | Prisma.TutorProfilesScalarWhereInput[]
}

export type IntFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type NullableIntFieldUpdateOperationsInput = {
  set?: number | null
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type FloatFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type TutorProfilesCreateNestedOneWithoutBookingsInput = {
  create?: Prisma.XOR<Prisma.TutorProfilesCreateWithoutBookingsInput, Prisma.TutorProfilesUncheckedCreateWithoutBookingsInput>
  connectOrCreate?: Prisma.TutorProfilesCreateOrConnectWithoutBookingsInput
  connect?: Prisma.TutorProfilesWhereUniqueInput
}

export type TutorProfilesUpdateOneRequiredWithoutBookingsNestedInput = {
  create?: Prisma.XOR<Prisma.TutorProfilesCreateWithoutBookingsInput, Prisma.TutorProfilesUncheckedCreateWithoutBookingsInput>
  connectOrCreate?: Prisma.TutorProfilesCreateOrConnectWithoutBookingsInput
  upsert?: Prisma.TutorProfilesUpsertWithoutBookingsInput
  connect?: Prisma.TutorProfilesWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.TutorProfilesUpdateToOneWithWhereWithoutBookingsInput, Prisma.TutorProfilesUpdateWithoutBookingsInput>, Prisma.TutorProfilesUncheckedUpdateWithoutBookingsInput>
}

export type TutorProfilesCreateNestedManyWithoutCategoriesInput = {
  create?: Prisma.XOR<Prisma.TutorProfilesCreateWithoutCategoriesInput, Prisma.TutorProfilesUncheckedCreateWithoutCategoriesInput> | Prisma.TutorProfilesCreateWithoutCategoriesInput[] | Prisma.TutorProfilesUncheckedCreateWithoutCategoriesInput[]
  connectOrCreate?: Prisma.TutorProfilesCreateOrConnectWithoutCategoriesInput | Prisma.TutorProfilesCreateOrConnectWithoutCategoriesInput[]
  connect?: Prisma.TutorProfilesWhereUniqueInput | Prisma.TutorProfilesWhereUniqueInput[]
}

export type TutorProfilesUncheckedCreateNestedManyWithoutCategoriesInput = {
  create?: Prisma.XOR<Prisma.TutorProfilesCreateWithoutCategoriesInput, Prisma.TutorProfilesUncheckedCreateWithoutCategoriesInput> | Prisma.TutorProfilesCreateWithoutCategoriesInput[] | Prisma.TutorProfilesUncheckedCreateWithoutCategoriesInput[]
  connectOrCreate?: Prisma.TutorProfilesCreateOrConnectWithoutCategoriesInput | Prisma.TutorProfilesCreateOrConnectWithoutCategoriesInput[]
  connect?: Prisma.TutorProfilesWhereUniqueInput | Prisma.TutorProfilesWhereUniqueInput[]
}

export type TutorProfilesUpdateManyWithoutCategoriesNestedInput = {
  create?: Prisma.XOR<Prisma.TutorProfilesCreateWithoutCategoriesInput, Prisma.TutorProfilesUncheckedCreateWithoutCategoriesInput> | Prisma.TutorProfilesCreateWithoutCategoriesInput[] | Prisma.TutorProfilesUncheckedCreateWithoutCategoriesInput[]
  connectOrCreate?: Prisma.TutorProfilesCreateOrConnectWithoutCategoriesInput | Prisma.TutorProfilesCreateOrConnectWithoutCategoriesInput[]
  upsert?: Prisma.TutorProfilesUpsertWithWhereUniqueWithoutCategoriesInput | Prisma.TutorProfilesUpsertWithWhereUniqueWithoutCategoriesInput[]
  set?: Prisma.TutorProfilesWhereUniqueInput | Prisma.TutorProfilesWhereUniqueInput[]
  disconnect?: Prisma.TutorProfilesWhereUniqueInput | Prisma.TutorProfilesWhereUniqueInput[]
  delete?: Prisma.TutorProfilesWhereUniqueInput | Prisma.TutorProfilesWhereUniqueInput[]
  connect?: Prisma.TutorProfilesWhereUniqueInput | Prisma.TutorProfilesWhereUniqueInput[]
  update?: Prisma.TutorProfilesUpdateWithWhereUniqueWithoutCategoriesInput | Prisma.TutorProfilesUpdateWithWhereUniqueWithoutCategoriesInput[]
  updateMany?: Prisma.TutorProfilesUpdateManyWithWhereWithoutCategoriesInput | Prisma.TutorProfilesUpdateManyWithWhereWithoutCategoriesInput[]
  deleteMany?: Prisma.TutorProfilesScalarWhereInput | Prisma.TutorProfilesScalarWhereInput[]
}

export type TutorProfilesUncheckedUpdateManyWithoutCategoriesNestedInput = {
  create?: Prisma.XOR<Prisma.TutorProfilesCreateWithoutCategoriesInput, Prisma.TutorProfilesUncheckedCreateWithoutCategoriesInput> | Prisma.TutorProfilesCreateWithoutCategoriesInput[] | Prisma.TutorProfilesUncheckedCreateWithoutCategoriesInput[]
  connectOrCreate?: Prisma.TutorProfilesCreateOrConnectWithoutCategoriesInput | Prisma.TutorProfilesCreateOrConnectWithoutCategoriesInput[]
  upsert?: Prisma.TutorProfilesUpsertWithWhereUniqueWithoutCategoriesInput | Prisma.TutorProfilesUpsertWithWhereUniqueWithoutCategoriesInput[]
  set?: Prisma.TutorProfilesWhereUniqueInput | Prisma.TutorProfilesWhereUniqueInput[]
  disconnect?: Prisma.TutorProfilesWhereUniqueInput | Prisma.TutorProfilesWhereUniqueInput[]
  delete?: Prisma.TutorProfilesWhereUniqueInput | Prisma.TutorProfilesWhereUniqueInput[]
  connect?: Prisma.TutorProfilesWhereUniqueInput | Prisma.TutorProfilesWhereUniqueInput[]
  update?: Prisma.TutorProfilesUpdateWithWhereUniqueWithoutCategoriesInput | Prisma.TutorProfilesUpdateWithWhereUniqueWithoutCategoriesInput[]
  updateMany?: Prisma.TutorProfilesUpdateManyWithWhereWithoutCategoriesInput | Prisma.TutorProfilesUpdateManyWithWhereWithoutCategoriesInput[]
  deleteMany?: Prisma.TutorProfilesScalarWhereInput | Prisma.TutorProfilesScalarWhereInput[]
}

export type TutorProfilesCreateNestedOneWithoutReviewsInput = {
  create?: Prisma.XOR<Prisma.TutorProfilesCreateWithoutReviewsInput, Prisma.TutorProfilesUncheckedCreateWithoutReviewsInput>
  connectOrCreate?: Prisma.TutorProfilesCreateOrConnectWithoutReviewsInput
  connect?: Prisma.TutorProfilesWhereUniqueInput
}

export type TutorProfilesUpdateOneRequiredWithoutReviewsNestedInput = {
  create?: Prisma.XOR<Prisma.TutorProfilesCreateWithoutReviewsInput, Prisma.TutorProfilesUncheckedCreateWithoutReviewsInput>
  connectOrCreate?: Prisma.TutorProfilesCreateOrConnectWithoutReviewsInput
  upsert?: Prisma.TutorProfilesUpsertWithoutReviewsInput
  connect?: Prisma.TutorProfilesWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.TutorProfilesUpdateToOneWithWhereWithoutReviewsInput, Prisma.TutorProfilesUpdateWithoutReviewsInput>, Prisma.TutorProfilesUncheckedUpdateWithoutReviewsInput>
}

export type TutorProfilesCreateWithoutUserInput = {
  id?: string
  bio?: string | null
  hourlyRate: number
  experience?: number | null
  averageRating?: number
  availability: Prisma.JsonNullValueInput | runtime.InputJsonValue
  categories?: Prisma.CategoryCreateNestedManyWithoutTutorProfilesInput
  bookings?: Prisma.BookingsCreateNestedManyWithoutTutorInput
  reviews?: Prisma.ReviewCreateNestedManyWithoutTutorInput
}

export type TutorProfilesUncheckedCreateWithoutUserInput = {
  id?: string
  bio?: string | null
  hourlyRate: number
  experience?: number | null
  averageRating?: number
  availability: Prisma.JsonNullValueInput | runtime.InputJsonValue
  categories?: Prisma.CategoryUncheckedCreateNestedManyWithoutTutorProfilesInput
  bookings?: Prisma.BookingsUncheckedCreateNestedManyWithoutTutorInput
  reviews?: Prisma.ReviewUncheckedCreateNestedManyWithoutTutorInput
}

export type TutorProfilesCreateOrConnectWithoutUserInput = {
  where: Prisma.TutorProfilesWhereUniqueInput
  create: Prisma.XOR<Prisma.TutorProfilesCreateWithoutUserInput, Prisma.TutorProfilesUncheckedCreateWithoutUserInput>
}

export type TutorProfilesCreateManyUserInputEnvelope = {
  data: Prisma.TutorProfilesCreateManyUserInput | Prisma.TutorProfilesCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type TutorProfilesUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.TutorProfilesWhereUniqueInput
  update: Prisma.XOR<Prisma.TutorProfilesUpdateWithoutUserInput, Prisma.TutorProfilesUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.TutorProfilesCreateWithoutUserInput, Prisma.TutorProfilesUncheckedCreateWithoutUserInput>
}

export type TutorProfilesUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.TutorProfilesWhereUniqueInput
  data: Prisma.XOR<Prisma.TutorProfilesUpdateWithoutUserInput, Prisma.TutorProfilesUncheckedUpdateWithoutUserInput>
}

export type TutorProfilesUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.TutorProfilesScalarWhereInput
  data: Prisma.XOR<Prisma.TutorProfilesUpdateManyMutationInput, Prisma.TutorProfilesUncheckedUpdateManyWithoutUserInput>
}

export type TutorProfilesScalarWhereInput = {
  AND?: Prisma.TutorProfilesScalarWhereInput | Prisma.TutorProfilesScalarWhereInput[]
  OR?: Prisma.TutorProfilesScalarWhereInput[]
  NOT?: Prisma.TutorProfilesScalarWhereInput | Prisma.TutorProfilesScalarWhereInput[]
  id?: Prisma.StringFilter<"TutorProfiles"> | string
  userId?: Prisma.StringFilter<"TutorProfiles"> | string
  bio?: Prisma.StringNullableFilter<"TutorProfiles"> | string | null
  hourlyRate?: Prisma.IntFilter<"TutorProfiles"> | number
  experience?: Prisma.IntNullableFilter<"TutorProfiles"> | number | null
  averageRating?: Prisma.FloatFilter<"TutorProfiles"> | number
  availability?: Prisma.JsonFilter<"TutorProfiles">
}

export type TutorProfilesCreateWithoutBookingsInput = {
  id?: string
  bio?: string | null
  hourlyRate: number
  experience?: number | null
  averageRating?: number
  availability: Prisma.JsonNullValueInput | runtime.InputJsonValue
  user: Prisma.UserCreateNestedOneWithoutTutorProfilesInput
  categories?: Prisma.CategoryCreateNestedManyWithoutTutorProfilesInput
  reviews?: Prisma.ReviewCreateNestedManyWithoutTutorInput
}

export type TutorProfilesUncheckedCreateWithoutBookingsInput = {
  id?: string
  userId: string
  bio?: string | null
  hourlyRate: number
  experience?: number | null
  averageRating?: number
  availability: Prisma.JsonNullValueInput | runtime.InputJsonValue
  categories?: Prisma.CategoryUncheckedCreateNestedManyWithoutTutorProfilesInput
  reviews?: Prisma.ReviewUncheckedCreateNestedManyWithoutTutorInput
}

export type TutorProfilesCreateOrConnectWithoutBookingsInput = {
  where: Prisma.TutorProfilesWhereUniqueInput
  create: Prisma.XOR<Prisma.TutorProfilesCreateWithoutBookingsInput, Prisma.TutorProfilesUncheckedCreateWithoutBookingsInput>
}

export type TutorProfilesUpsertWithoutBookingsInput = {
  update: Prisma.XOR<Prisma.TutorProfilesUpdateWithoutBookingsInput, Prisma.TutorProfilesUncheckedUpdateWithoutBookingsInput>
  create: Prisma.XOR<Prisma.TutorProfilesCreateWithoutBookingsInput, Prisma.TutorProfilesUncheckedCreateWithoutBookingsInput>
  where?: Prisma.TutorProfilesWhereInput
}

export type TutorProfilesUpdateToOneWithWhereWithoutBookingsInput = {
  where?: Prisma.TutorProfilesWhereInput
  data: Prisma.XOR<Prisma.TutorProfilesUpdateWithoutBookingsInput, Prisma.TutorProfilesUncheckedUpdateWithoutBookingsInput>
}

export type TutorProfilesUpdateWithoutBookingsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  bio?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  hourlyRate?: Prisma.IntFieldUpdateOperationsInput | number
  experience?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  averageRating?: Prisma.FloatFieldUpdateOperationsInput | number
  availability?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  user?: Prisma.UserUpdateOneRequiredWithoutTutorProfilesNestedInput
  categories?: Prisma.CategoryUpdateManyWithoutTutorProfilesNestedInput
  reviews?: Prisma.ReviewUpdateManyWithoutTutorNestedInput
}

export type TutorProfilesUncheckedUpdateWithoutBookingsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  bio?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  hourlyRate?: Prisma.IntFieldUpdateOperationsInput | number
  experience?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  averageRating?: Prisma.FloatFieldUpdateOperationsInput | number
  availability?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  categories?: Prisma.CategoryUncheckedUpdateManyWithoutTutorProfilesNestedInput
  reviews?: Prisma.ReviewUncheckedUpdateManyWithoutTutorNestedInput
}

export type TutorProfilesCreateWithoutCategoriesInput = {
  id?: string
  bio?: string | null
  hourlyRate: number
  experience?: number | null
  averageRating?: number
  availability: Prisma.JsonNullValueInput | runtime.InputJsonValue
  user: Prisma.UserCreateNestedOneWithoutTutorProfilesInput
  bookings?: Prisma.BookingsCreateNestedManyWithoutTutorInput
  reviews?: Prisma.ReviewCreateNestedManyWithoutTutorInput
}

export type TutorProfilesUncheckedCreateWithoutCategoriesInput = {
  id?: string
  userId: string
  bio?: string | null
  hourlyRate: number
  experience?: number | null
  averageRating?: number
  availability: Prisma.JsonNullValueInput | runtime.InputJsonValue
  bookings?: Prisma.BookingsUncheckedCreateNestedManyWithoutTutorInput
  reviews?: Prisma.ReviewUncheckedCreateNestedManyWithoutTutorInput
}

export type TutorProfilesCreateOrConnectWithoutCategoriesInput = {
  where: Prisma.TutorProfilesWhereUniqueInput
  create: Prisma.XOR<Prisma.TutorProfilesCreateWithoutCategoriesInput, Prisma.TutorProfilesUncheckedCreateWithoutCategoriesInput>
}

export type TutorProfilesUpsertWithWhereUniqueWithoutCategoriesInput = {
  where: Prisma.TutorProfilesWhereUniqueInput
  update: Prisma.XOR<Prisma.TutorProfilesUpdateWithoutCategoriesInput, Prisma.TutorProfilesUncheckedUpdateWithoutCategoriesInput>
  create: Prisma.XOR<Prisma.TutorProfilesCreateWithoutCategoriesInput, Prisma.TutorProfilesUncheckedCreateWithoutCategoriesInput>
}

export type TutorProfilesUpdateWithWhereUniqueWithoutCategoriesInput = {
  where: Prisma.TutorProfilesWhereUniqueInput
  data: Prisma.XOR<Prisma.TutorProfilesUpdateWithoutCategoriesInput, Prisma.TutorProfilesUncheckedUpdateWithoutCategoriesInput>
}

export type TutorProfilesUpdateManyWithWhereWithoutCategoriesInput = {
  where: Prisma.TutorProfilesScalarWhereInput
  data: Prisma.XOR<Prisma.TutorProfilesUpdateManyMutationInput, Prisma.TutorProfilesUncheckedUpdateManyWithoutCategoriesInput>
}

export type TutorProfilesCreateWithoutReviewsInput = {
  id?: string
  bio?: string | null
  hourlyRate: number
  experience?: number | null
  averageRating?: number
  availability: Prisma.JsonNullValueInput | runtime.InputJsonValue
  user: Prisma.UserCreateNestedOneWithoutTutorProfilesInput
  categories?: Prisma.CategoryCreateNestedManyWithoutTutorProfilesInput
  bookings?: Prisma.BookingsCreateNestedManyWithoutTutorInput
}

export type TutorProfilesUncheckedCreateWithoutReviewsInput = {
  id?: string
  userId: string
  bio?: string | null
  hourlyRate: number
  experience?: number | null
  averageRating?: number
  availability: Prisma.JsonNullValueInput | runtime.InputJsonValue
  categories?: Prisma.CategoryUncheckedCreateNestedManyWithoutTutorProfilesInput
  bookings?: Prisma.BookingsUncheckedCreateNestedManyWithoutTutorInput
}

export type TutorProfilesCreateOrConnectWithoutReviewsInput = {
  where: Prisma.TutorProfilesWhereUniqueInput
  create: Prisma.XOR<Prisma.TutorProfilesCreateWithoutReviewsInput, Prisma.TutorProfilesUncheckedCreateWithoutReviewsInput>
}

export type TutorProfilesUpsertWithoutReviewsInput = {
  update: Prisma.XOR<Prisma.TutorProfilesUpdateWithoutReviewsInput, Prisma.TutorProfilesUncheckedUpdateWithoutReviewsInput>
  create: Prisma.XOR<Prisma.TutorProfilesCreateWithoutReviewsInput, Prisma.TutorProfilesUncheckedCreateWithoutReviewsInput>
  where?: Prisma.TutorProfilesWhereInput
}

export type TutorProfilesUpdateToOneWithWhereWithoutReviewsInput = {
  where?: Prisma.TutorProfilesWhereInput
  data: Prisma.XOR<Prisma.TutorProfilesUpdateWithoutReviewsInput, Prisma.TutorProfilesUncheckedUpdateWithoutReviewsInput>
}

export type TutorProfilesUpdateWithoutReviewsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  bio?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  hourlyRate?: Prisma.IntFieldUpdateOperationsInput | number
  experience?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  averageRating?: Prisma.FloatFieldUpdateOperationsInput | number
  availability?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  user?: Prisma.UserUpdateOneRequiredWithoutTutorProfilesNestedInput
  categories?: Prisma.CategoryUpdateManyWithoutTutorProfilesNestedInput
  bookings?: Prisma.BookingsUpdateManyWithoutTutorNestedInput
}

export type TutorProfilesUncheckedUpdateWithoutReviewsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  bio?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  hourlyRate?: Prisma.IntFieldUpdateOperationsInput | number
  experience?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  averageRating?: Prisma.FloatFieldUpdateOperationsInput | number
  availability?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  categories?: Prisma.CategoryUncheckedUpdateManyWithoutTutorProfilesNestedInput
  bookings?: Prisma.BookingsUncheckedUpdateManyWithoutTutorNestedInput
}

export type TutorProfilesCreateManyUserInput = {
  id?: string
  bio?: string | null
  hourlyRate: number
  experience?: number | null
  averageRating?: number
  availability: Prisma.JsonNullValueInput | runtime.InputJsonValue
}

export type TutorProfilesUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  bio?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  hourlyRate?: Prisma.IntFieldUpdateOperationsInput | number
  experience?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  averageRating?: Prisma.FloatFieldUpdateOperationsInput | number
  availability?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  categories?: Prisma.CategoryUpdateManyWithoutTutorProfilesNestedInput
  bookings?: Prisma.BookingsUpdateManyWithoutTutorNestedInput
  reviews?: Prisma.ReviewUpdateManyWithoutTutorNestedInput
}

export type TutorProfilesUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  bio?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  hourlyRate?: Prisma.IntFieldUpdateOperationsInput | number
  experience?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  averageRating?: Prisma.FloatFieldUpdateOperationsInput | number
  availability?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  categories?: Prisma.CategoryUncheckedUpdateManyWithoutTutorProfilesNestedInput
  bookings?: Prisma.BookingsUncheckedUpdateManyWithoutTutorNestedInput
  reviews?: Prisma.ReviewUncheckedUpdateManyWithoutTutorNestedInput
}

export type TutorProfilesUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  bio?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  hourlyRate?: Prisma.IntFieldUpdateOperationsInput | number
  experience?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  averageRating?: Prisma.FloatFieldUpdateOperationsInput | number
  availability?: Prisma.JsonNullValueInput | runtime.InputJsonValue
}

export type TutorProfilesUpdateWithoutCategoriesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  bio?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  hourlyRate?: Prisma.IntFieldUpdateOperationsInput | number
  experience?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  averageRating?: Prisma.FloatFieldUpdateOperationsInput | number
  availability?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  user?: Prisma.UserUpdateOneRequiredWithoutTutorProfilesNestedInput
  bookings?: Prisma.BookingsUpdateManyWithoutTutorNestedInput
  reviews?: Prisma.ReviewUpdateManyWithoutTutorNestedInput
}

export type TutorProfilesUncheckedUpdateWithoutCategoriesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  bio?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  hourlyRate?: Prisma.IntFieldUpdateOperationsInput | number
  experience?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  averageRating?: Prisma.FloatFieldUpdateOperationsInput | number
  availability?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  bookings?: Prisma.BookingsUncheckedUpdateManyWithoutTutorNestedInput
  reviews?: Prisma.ReviewUncheckedUpdateManyWithoutTutorNestedInput
}

export type TutorProfilesUncheckedUpdateManyWithoutCategoriesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  bio?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  hourlyRate?: Prisma.IntFieldUpdateOperationsInput | number
  experience?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  averageRating?: Prisma.FloatFieldUpdateOperationsInput | number
  availability?: Prisma.JsonNullValueInput | runtime.InputJsonValue
}


/**
 * Count Type TutorProfilesCountOutputType
 */

export type TutorProfilesCountOutputType = {
  categories: number
  bookings: number
  reviews: number
}

export type TutorProfilesCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  categories?: boolean | TutorProfilesCountOutputTypeCountCategoriesArgs
  bookings?: boolean | TutorProfilesCountOutputTypeCountBookingsArgs
  reviews?: boolean | TutorProfilesCountOutputTypeCountReviewsArgs
}

/**
 * TutorProfilesCountOutputType without action
 */
export type TutorProfilesCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TutorProfilesCountOutputType
   */
  select?: Prisma.TutorProfilesCountOutputTypeSelect<ExtArgs> | null
}

/**
 * TutorProfilesCountOutputType without action
 */
export type TutorProfilesCountOutputTypeCountCategoriesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.CategoryWhereInput
}

/**
 * TutorProfilesCountOutputType without action
 */
export type TutorProfilesCountOutputTypeCountBookingsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.BookingsWhereInput
}

/**
 * TutorProfilesCountOutputType without action
 */
export type TutorProfilesCountOutputTypeCountReviewsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ReviewWhereInput
}


export type TutorProfilesSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  bio?: boolean
  hourlyRate?: boolean
  experience?: boolean
  averageRating?: boolean
  availability?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  categories?: boolean | Prisma.TutorProfiles$categoriesArgs<ExtArgs>
  bookings?: boolean | Prisma.TutorProfiles$bookingsArgs<ExtArgs>
  reviews?: boolean | Prisma.TutorProfiles$reviewsArgs<ExtArgs>
  _count?: boolean | Prisma.TutorProfilesCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["tutorProfiles"]>

export type TutorProfilesSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  bio?: boolean
  hourlyRate?: boolean
  experience?: boolean
  averageRating?: boolean
  availability?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["tutorProfiles"]>

export type TutorProfilesSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  bio?: boolean
  hourlyRate?: boolean
  experience?: boolean
  averageRating?: boolean
  availability?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["tutorProfiles"]>

export type TutorProfilesSelectScalar = {
  id?: boolean
  userId?: boolean
  bio?: boolean
  hourlyRate?: boolean
  experience?: boolean
  averageRating?: boolean
  availability?: boolean
}

export type TutorProfilesOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "userId" | "bio" | "hourlyRate" | "experience" | "averageRating" | "availability", ExtArgs["result"]["tutorProfiles"]>
export type TutorProfilesInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  categories?: boolean | Prisma.TutorProfiles$categoriesArgs<ExtArgs>
  bookings?: boolean | Prisma.TutorProfiles$bookingsArgs<ExtArgs>
  reviews?: boolean | Prisma.TutorProfiles$reviewsArgs<ExtArgs>
  _count?: boolean | Prisma.TutorProfilesCountOutputTypeDefaultArgs<ExtArgs>
}
export type TutorProfilesIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type TutorProfilesIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}

export type $TutorProfilesPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "TutorProfiles"
  objects: {
    user: Prisma.$UserPayload<ExtArgs>
    categories: Prisma.$CategoryPayload<ExtArgs>[]
    bookings: Prisma.$BookingsPayload<ExtArgs>[]
    reviews: Prisma.$ReviewPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    userId: string
    bio: string | null
    hourlyRate: number
    experience: number | null
    averageRating: number
    availability: runtime.JsonValue
  }, ExtArgs["result"]["tutorProfiles"]>
  composites: {}
}

export type TutorProfilesGetPayload<S extends boolean | null | undefined | TutorProfilesDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$TutorProfilesPayload, S>

export type TutorProfilesCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<TutorProfilesFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: TutorProfilesCountAggregateInputType | true
  }

export interface TutorProfilesDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['TutorProfiles'], meta: { name: 'TutorProfiles' } }
  /**
   * Find zero or one TutorProfiles that matches the filter.
   * @param {TutorProfilesFindUniqueArgs} args - Arguments to find a TutorProfiles
   * @example
   * // Get one TutorProfiles
   * const tutorProfiles = await prisma.tutorProfiles.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends TutorProfilesFindUniqueArgs>(args: Prisma.SelectSubset<T, TutorProfilesFindUniqueArgs<ExtArgs>>): Prisma.Prisma__TutorProfilesClient<runtime.Types.Result.GetResult<Prisma.$TutorProfilesPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one TutorProfiles that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {TutorProfilesFindUniqueOrThrowArgs} args - Arguments to find a TutorProfiles
   * @example
   * // Get one TutorProfiles
   * const tutorProfiles = await prisma.tutorProfiles.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends TutorProfilesFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, TutorProfilesFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__TutorProfilesClient<runtime.Types.Result.GetResult<Prisma.$TutorProfilesPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first TutorProfiles that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TutorProfilesFindFirstArgs} args - Arguments to find a TutorProfiles
   * @example
   * // Get one TutorProfiles
   * const tutorProfiles = await prisma.tutorProfiles.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends TutorProfilesFindFirstArgs>(args?: Prisma.SelectSubset<T, TutorProfilesFindFirstArgs<ExtArgs>>): Prisma.Prisma__TutorProfilesClient<runtime.Types.Result.GetResult<Prisma.$TutorProfilesPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first TutorProfiles that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TutorProfilesFindFirstOrThrowArgs} args - Arguments to find a TutorProfiles
   * @example
   * // Get one TutorProfiles
   * const tutorProfiles = await prisma.tutorProfiles.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends TutorProfilesFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, TutorProfilesFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__TutorProfilesClient<runtime.Types.Result.GetResult<Prisma.$TutorProfilesPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more TutorProfiles that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TutorProfilesFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all TutorProfiles
   * const tutorProfiles = await prisma.tutorProfiles.findMany()
   * 
   * // Get first 10 TutorProfiles
   * const tutorProfiles = await prisma.tutorProfiles.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const tutorProfilesWithIdOnly = await prisma.tutorProfiles.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends TutorProfilesFindManyArgs>(args?: Prisma.SelectSubset<T, TutorProfilesFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TutorProfilesPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a TutorProfiles.
   * @param {TutorProfilesCreateArgs} args - Arguments to create a TutorProfiles.
   * @example
   * // Create one TutorProfiles
   * const TutorProfiles = await prisma.tutorProfiles.create({
   *   data: {
   *     // ... data to create a TutorProfiles
   *   }
   * })
   * 
   */
  create<T extends TutorProfilesCreateArgs>(args: Prisma.SelectSubset<T, TutorProfilesCreateArgs<ExtArgs>>): Prisma.Prisma__TutorProfilesClient<runtime.Types.Result.GetResult<Prisma.$TutorProfilesPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many TutorProfiles.
   * @param {TutorProfilesCreateManyArgs} args - Arguments to create many TutorProfiles.
   * @example
   * // Create many TutorProfiles
   * const tutorProfiles = await prisma.tutorProfiles.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends TutorProfilesCreateManyArgs>(args?: Prisma.SelectSubset<T, TutorProfilesCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many TutorProfiles and returns the data saved in the database.
   * @param {TutorProfilesCreateManyAndReturnArgs} args - Arguments to create many TutorProfiles.
   * @example
   * // Create many TutorProfiles
   * const tutorProfiles = await prisma.tutorProfiles.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many TutorProfiles and only return the `id`
   * const tutorProfilesWithIdOnly = await prisma.tutorProfiles.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends TutorProfilesCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, TutorProfilesCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TutorProfilesPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a TutorProfiles.
   * @param {TutorProfilesDeleteArgs} args - Arguments to delete one TutorProfiles.
   * @example
   * // Delete one TutorProfiles
   * const TutorProfiles = await prisma.tutorProfiles.delete({
   *   where: {
   *     // ... filter to delete one TutorProfiles
   *   }
   * })
   * 
   */
  delete<T extends TutorProfilesDeleteArgs>(args: Prisma.SelectSubset<T, TutorProfilesDeleteArgs<ExtArgs>>): Prisma.Prisma__TutorProfilesClient<runtime.Types.Result.GetResult<Prisma.$TutorProfilesPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one TutorProfiles.
   * @param {TutorProfilesUpdateArgs} args - Arguments to update one TutorProfiles.
   * @example
   * // Update one TutorProfiles
   * const tutorProfiles = await prisma.tutorProfiles.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends TutorProfilesUpdateArgs>(args: Prisma.SelectSubset<T, TutorProfilesUpdateArgs<ExtArgs>>): Prisma.Prisma__TutorProfilesClient<runtime.Types.Result.GetResult<Prisma.$TutorProfilesPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more TutorProfiles.
   * @param {TutorProfilesDeleteManyArgs} args - Arguments to filter TutorProfiles to delete.
   * @example
   * // Delete a few TutorProfiles
   * const { count } = await prisma.tutorProfiles.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends TutorProfilesDeleteManyArgs>(args?: Prisma.SelectSubset<T, TutorProfilesDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more TutorProfiles.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TutorProfilesUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many TutorProfiles
   * const tutorProfiles = await prisma.tutorProfiles.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends TutorProfilesUpdateManyArgs>(args: Prisma.SelectSubset<T, TutorProfilesUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more TutorProfiles and returns the data updated in the database.
   * @param {TutorProfilesUpdateManyAndReturnArgs} args - Arguments to update many TutorProfiles.
   * @example
   * // Update many TutorProfiles
   * const tutorProfiles = await prisma.tutorProfiles.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more TutorProfiles and only return the `id`
   * const tutorProfilesWithIdOnly = await prisma.tutorProfiles.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends TutorProfilesUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, TutorProfilesUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TutorProfilesPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one TutorProfiles.
   * @param {TutorProfilesUpsertArgs} args - Arguments to update or create a TutorProfiles.
   * @example
   * // Update or create a TutorProfiles
   * const tutorProfiles = await prisma.tutorProfiles.upsert({
   *   create: {
   *     // ... data to create a TutorProfiles
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the TutorProfiles we want to update
   *   }
   * })
   */
  upsert<T extends TutorProfilesUpsertArgs>(args: Prisma.SelectSubset<T, TutorProfilesUpsertArgs<ExtArgs>>): Prisma.Prisma__TutorProfilesClient<runtime.Types.Result.GetResult<Prisma.$TutorProfilesPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of TutorProfiles.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TutorProfilesCountArgs} args - Arguments to filter TutorProfiles to count.
   * @example
   * // Count the number of TutorProfiles
   * const count = await prisma.tutorProfiles.count({
   *   where: {
   *     // ... the filter for the TutorProfiles we want to count
   *   }
   * })
  **/
  count<T extends TutorProfilesCountArgs>(
    args?: Prisma.Subset<T, TutorProfilesCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], TutorProfilesCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a TutorProfiles.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TutorProfilesAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends TutorProfilesAggregateArgs>(args: Prisma.Subset<T, TutorProfilesAggregateArgs>): Prisma.PrismaPromise<GetTutorProfilesAggregateType<T>>

  /**
   * Group by TutorProfiles.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TutorProfilesGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends TutorProfilesGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: TutorProfilesGroupByArgs['orderBy'] }
      : { orderBy?: TutorProfilesGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, TutorProfilesGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetTutorProfilesGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the TutorProfiles model
 */
readonly fields: TutorProfilesFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for TutorProfiles.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__TutorProfilesClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  categories<T extends Prisma.TutorProfiles$categoriesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.TutorProfiles$categoriesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CategoryPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  bookings<T extends Prisma.TutorProfiles$bookingsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.TutorProfiles$bookingsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$BookingsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  reviews<T extends Prisma.TutorProfiles$reviewsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.TutorProfiles$reviewsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ReviewPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the TutorProfiles model
 */
export interface TutorProfilesFieldRefs {
  readonly id: Prisma.FieldRef<"TutorProfiles", 'String'>
  readonly userId: Prisma.FieldRef<"TutorProfiles", 'String'>
  readonly bio: Prisma.FieldRef<"TutorProfiles", 'String'>
  readonly hourlyRate: Prisma.FieldRef<"TutorProfiles", 'Int'>
  readonly experience: Prisma.FieldRef<"TutorProfiles", 'Int'>
  readonly averageRating: Prisma.FieldRef<"TutorProfiles", 'Float'>
  readonly availability: Prisma.FieldRef<"TutorProfiles", 'Json'>
}
    

// Custom InputTypes
/**
 * TutorProfiles findUnique
 */
export type TutorProfilesFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TutorProfiles
   */
  select?: Prisma.TutorProfilesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TutorProfiles
   */
  omit?: Prisma.TutorProfilesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TutorProfilesInclude<ExtArgs> | null
  /**
   * Filter, which TutorProfiles to fetch.
   */
  where: Prisma.TutorProfilesWhereUniqueInput
}

/**
 * TutorProfiles findUniqueOrThrow
 */
export type TutorProfilesFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TutorProfiles
   */
  select?: Prisma.TutorProfilesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TutorProfiles
   */
  omit?: Prisma.TutorProfilesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TutorProfilesInclude<ExtArgs> | null
  /**
   * Filter, which TutorProfiles to fetch.
   */
  where: Prisma.TutorProfilesWhereUniqueInput
}

/**
 * TutorProfiles findFirst
 */
export type TutorProfilesFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TutorProfiles
   */
  select?: Prisma.TutorProfilesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TutorProfiles
   */
  omit?: Prisma.TutorProfilesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TutorProfilesInclude<ExtArgs> | null
  /**
   * Filter, which TutorProfiles to fetch.
   */
  where?: Prisma.TutorProfilesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TutorProfiles to fetch.
   */
  orderBy?: Prisma.TutorProfilesOrderByWithRelationInput | Prisma.TutorProfilesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for TutorProfiles.
   */
  cursor?: Prisma.TutorProfilesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TutorProfiles from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TutorProfiles.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TutorProfiles.
   */
  distinct?: Prisma.TutorProfilesScalarFieldEnum | Prisma.TutorProfilesScalarFieldEnum[]
}

/**
 * TutorProfiles findFirstOrThrow
 */
export type TutorProfilesFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TutorProfiles
   */
  select?: Prisma.TutorProfilesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TutorProfiles
   */
  omit?: Prisma.TutorProfilesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TutorProfilesInclude<ExtArgs> | null
  /**
   * Filter, which TutorProfiles to fetch.
   */
  where?: Prisma.TutorProfilesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TutorProfiles to fetch.
   */
  orderBy?: Prisma.TutorProfilesOrderByWithRelationInput | Prisma.TutorProfilesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for TutorProfiles.
   */
  cursor?: Prisma.TutorProfilesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TutorProfiles from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TutorProfiles.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TutorProfiles.
   */
  distinct?: Prisma.TutorProfilesScalarFieldEnum | Prisma.TutorProfilesScalarFieldEnum[]
}

/**
 * TutorProfiles findMany
 */
export type TutorProfilesFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TutorProfiles
   */
  select?: Prisma.TutorProfilesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TutorProfiles
   */
  omit?: Prisma.TutorProfilesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TutorProfilesInclude<ExtArgs> | null
  /**
   * Filter, which TutorProfiles to fetch.
   */
  where?: Prisma.TutorProfilesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TutorProfiles to fetch.
   */
  orderBy?: Prisma.TutorProfilesOrderByWithRelationInput | Prisma.TutorProfilesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing TutorProfiles.
   */
  cursor?: Prisma.TutorProfilesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TutorProfiles from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TutorProfiles.
   */
  skip?: number
  distinct?: Prisma.TutorProfilesScalarFieldEnum | Prisma.TutorProfilesScalarFieldEnum[]
}

/**
 * TutorProfiles create
 */
export type TutorProfilesCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TutorProfiles
   */
  select?: Prisma.TutorProfilesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TutorProfiles
   */
  omit?: Prisma.TutorProfilesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TutorProfilesInclude<ExtArgs> | null
  /**
   * The data needed to create a TutorProfiles.
   */
  data: Prisma.XOR<Prisma.TutorProfilesCreateInput, Prisma.TutorProfilesUncheckedCreateInput>
}

/**
 * TutorProfiles createMany
 */
export type TutorProfilesCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many TutorProfiles.
   */
  data: Prisma.TutorProfilesCreateManyInput | Prisma.TutorProfilesCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * TutorProfiles createManyAndReturn
 */
export type TutorProfilesCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TutorProfiles
   */
  select?: Prisma.TutorProfilesSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the TutorProfiles
   */
  omit?: Prisma.TutorProfilesOmit<ExtArgs> | null
  /**
   * The data used to create many TutorProfiles.
   */
  data: Prisma.TutorProfilesCreateManyInput | Prisma.TutorProfilesCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TutorProfilesIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * TutorProfiles update
 */
export type TutorProfilesUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TutorProfiles
   */
  select?: Prisma.TutorProfilesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TutorProfiles
   */
  omit?: Prisma.TutorProfilesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TutorProfilesInclude<ExtArgs> | null
  /**
   * The data needed to update a TutorProfiles.
   */
  data: Prisma.XOR<Prisma.TutorProfilesUpdateInput, Prisma.TutorProfilesUncheckedUpdateInput>
  /**
   * Choose, which TutorProfiles to update.
   */
  where: Prisma.TutorProfilesWhereUniqueInput
}

/**
 * TutorProfiles updateMany
 */
export type TutorProfilesUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update TutorProfiles.
   */
  data: Prisma.XOR<Prisma.TutorProfilesUpdateManyMutationInput, Prisma.TutorProfilesUncheckedUpdateManyInput>
  /**
   * Filter which TutorProfiles to update
   */
  where?: Prisma.TutorProfilesWhereInput
  /**
   * Limit how many TutorProfiles to update.
   */
  limit?: number
}

/**
 * TutorProfiles updateManyAndReturn
 */
export type TutorProfilesUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TutorProfiles
   */
  select?: Prisma.TutorProfilesSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the TutorProfiles
   */
  omit?: Prisma.TutorProfilesOmit<ExtArgs> | null
  /**
   * The data used to update TutorProfiles.
   */
  data: Prisma.XOR<Prisma.TutorProfilesUpdateManyMutationInput, Prisma.TutorProfilesUncheckedUpdateManyInput>
  /**
   * Filter which TutorProfiles to update
   */
  where?: Prisma.TutorProfilesWhereInput
  /**
   * Limit how many TutorProfiles to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TutorProfilesIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * TutorProfiles upsert
 */
export type TutorProfilesUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TutorProfiles
   */
  select?: Prisma.TutorProfilesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TutorProfiles
   */
  omit?: Prisma.TutorProfilesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TutorProfilesInclude<ExtArgs> | null
  /**
   * The filter to search for the TutorProfiles to update in case it exists.
   */
  where: Prisma.TutorProfilesWhereUniqueInput
  /**
   * In case the TutorProfiles found by the `where` argument doesn't exist, create a new TutorProfiles with this data.
   */
  create: Prisma.XOR<Prisma.TutorProfilesCreateInput, Prisma.TutorProfilesUncheckedCreateInput>
  /**
   * In case the TutorProfiles was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.TutorProfilesUpdateInput, Prisma.TutorProfilesUncheckedUpdateInput>
}

/**
 * TutorProfiles delete
 */
export type TutorProfilesDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TutorProfiles
   */
  select?: Prisma.TutorProfilesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TutorProfiles
   */
  omit?: Prisma.TutorProfilesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TutorProfilesInclude<ExtArgs> | null
  /**
   * Filter which TutorProfiles to delete.
   */
  where: Prisma.TutorProfilesWhereUniqueInput
}

/**
 * TutorProfiles deleteMany
 */
export type TutorProfilesDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which TutorProfiles to delete
   */
  where?: Prisma.TutorProfilesWhereInput
  /**
   * Limit how many TutorProfiles to delete.
   */
  limit?: number
}

/**
 * TutorProfiles.categories
 */
export type TutorProfiles$categoriesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Category
   */
  select?: Prisma.CategorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Category
   */
  omit?: Prisma.CategoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CategoryInclude<ExtArgs> | null
  where?: Prisma.CategoryWhereInput
  orderBy?: Prisma.CategoryOrderByWithRelationInput | Prisma.CategoryOrderByWithRelationInput[]
  cursor?: Prisma.CategoryWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.CategoryScalarFieldEnum | Prisma.CategoryScalarFieldEnum[]
}

/**
 * TutorProfiles.bookings
 */
export type TutorProfiles$bookingsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Bookings
   */
  select?: Prisma.BookingsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Bookings
   */
  omit?: Prisma.BookingsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BookingsInclude<ExtArgs> | null
  where?: Prisma.BookingsWhereInput
  orderBy?: Prisma.BookingsOrderByWithRelationInput | Prisma.BookingsOrderByWithRelationInput[]
  cursor?: Prisma.BookingsWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.BookingsScalarFieldEnum | Prisma.BookingsScalarFieldEnum[]
}

/**
 * TutorProfiles.reviews
 */
export type TutorProfiles$reviewsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Review
   */
  select?: Prisma.ReviewSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Review
   */
  omit?: Prisma.ReviewOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ReviewInclude<ExtArgs> | null
  where?: Prisma.ReviewWhereInput
  orderBy?: Prisma.ReviewOrderByWithRelationInput | Prisma.ReviewOrderByWithRelationInput[]
  cursor?: Prisma.ReviewWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.ReviewScalarFieldEnum | Prisma.ReviewScalarFieldEnum[]
}

/**
 * TutorProfiles without action
 */
export type TutorProfilesDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TutorProfiles
   */
  select?: Prisma.TutorProfilesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TutorProfiles
   */
  omit?: Prisma.TutorProfilesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TutorProfilesInclude<ExtArgs> | null
}
